baseURL = "/"
footnoteReturnLinkContents = "â†©"
title = "janwillem.xyz"
theme = "blank"

[params]
  AuthorName = "Jon Doe"
  Subtitle = "Hugo is Absurdly Fast!"

[permalinks]
  posts = "/:year/:month/:title/"
  
[taxonomies]
  tag      = "tags"
  category = "categories"
  
[markup.goldmark.renderer]
  unsafe= true
